#ifndef WEBADDR_H
#define WEBADDR_H

#define WEBAD	"http://dlj.chenag.com/bbs/info_op.asp?id=27062\
*\
http://code.google.com/intl/zh-CN/edu/courses.html\
*\
http://www.codecademy.com/#!/exercises/0\
*\
http://blog.jobbole.com/category/programmer/\
*\
http://www.cjb.net/cgi-bin/shell.cgi?action=contact&username=brucewang\
*\
http://www.verycd.com/search/folders/\
*\
http://translate.google.com.hk/?hl=&ie=UTF-8&text=&sl=en&tl=zh-CN\
*\
http://lxr.oss.org.cn/\
*\
http://503062.5sing.com/fcsong.aspx\
*\
http://www.in20years.com/\
*\
http://cet.99sushe.com/\
*\
http://www.allgraphicdesign.com/\
*\
http://www.sologig.com/\
*\
http://www.36kr.com/\
*\
http://www.dice.com/\
*\
http://wiki.ubuntu.org.cn/UbuntuSkills\
*\
http://www.chuangxin.com/recruit/campus/campus-software-development-engineer/\
*\
http://www.icili.com/emule/book/computer/\
*\
http://p2pu.org/en/\
*\
http://bbs.yingjiesheng.com/forum.php\
*\
http://www.google.cn/music/album?id=Bfe18b96cf4790f13\
*\
http://dynamic.cloud.vip.xunlei.com/user_task?userid=153404448&st=0&cache=1326772310\
*\
http://processing.org/learning/\
*\
http://web.qq.com/\
*\
http://bulo.hujiang.com/home?r=passport\
*\
http://www.ppurl.com/\
*\
http://www.diandian.com/home\
*\
https://mail.google.com/mail/?shva=1#inbox/1341ddffc7bba082\
*\
http://net.tutsplus.com/tutorials/html-css-techniques/30-html-best-practices-for-beginners/\
*\
https://plus.google.com/\
*\
https://www.linuxcare.com\
*\
http://ocw.mit.edu/index.htm\
*\
http://cslibrary.stanford.edu/\
*\
http://www.core.org.cn/\
*\
https://www.interviewstreet.com/challenges/dashboard/#problems\
*\
http://www.myoops.org/cocw/mit/index.htm\
*\
http://p2pu.org/en/\
*\
sp:\
*\
http://dongtaiwang.com/loc/software/fg/727/fg727p.exe\
*\
http://dongtaiwang.com/loc/software/fg/727/fg727p.zip\
*\
msr：\
*\
http://dongtaiwang.com/loc/software/fg/727/fg727x.exe\
*\
http://dongtaiwang.com/loc/software/fg/727/fg727x.zip\
*\
http://tech.163.com/special/00091T71/javashipin.html\
*\
http://www.java-cn.com/\
*\
http://tech.163.com/school/\
*\
http://www.kernel.org/\
*\
http://reg.29293.com/tui.aspx\
*\
"

#endif

